
import { Nav } from "@/components/Nav";
import { Barra, Footer, Nov } from "../components";
import Navbar from "../components/Navbar";

 

import "./globals.css";
import type { Metadata } from "next";

import { Inter,Poppins,Rubik,Dancing_Script,Lobster_Two,Abril_Fatface } from "next/font/google";

const inter = Inter({ subsets: ["latin"],variable:"--font-inter" });

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const abril_fatface = Abril_Fatface({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-abril-fatface',
  weight: [ '400']
});
const lobster_two = Lobster_Two({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lobster-two',
  weight: [ '400','700']
});

const dancing_script = Dancing_Script({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dancing-script',
  weight: ['400', '500', '600', '700']
});

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
  weight: [ '300', '400', '500', '600', '700', '800', '900']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body style={poppins.style} className={`bg-[#fff] ${inter.variable} ${poppins.variable} ${lobster_two.variable} ${dancing_script.variable} ${abril_fatface.variable} ${rubik.variable}`}>
        <div className="3xl:container mx-auto  min-h-screen ">
          <Barra/>
          <main className="">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
